version: "3.2"

services:
  records-db:
    image: influxdb:2.5.1
    restart: always
    ports:
      - "8071:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=root
      - DOCKER_INFLUXDB_INIT_ORG=at20057
      - DOCKER_INFLUXDB_INIT_BUCKET=hardware
    volumes:
      - influxdb-storage:/var/lib/influxdb

  stats-ms:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8070:8070"

volumes:
  influxdb-storage: